const motivationer = [
    "Tänk dig att varje sparad krona är som en liten superhjälte som kämpar för din ekonomiska frihet!",
    "Spara som om du planerade den mest episka semesterresan till en plats där pengar inte behövs!",
    "Varje sparat öre är som en applåd till din framtida jag – Bra jobbat!",
    "Kom ihåg, den som spar han har... mer att spendera på roliga saker senare!",
    "Se dina besparingar som en spel-poäng! Högre poäng = fler möjligheter!",
    "Spara idag, lev som en kung imorgon. Eller åtminstone som en väldigt nöjd hertig!",
    "Varje sparat öre är en biljett till ditt nästa stora äventyr. Packa dina väskor!",
    "Spara som om du skulle vinna en stor summa pengar imorgon – du vet aldrig vad som händer!",
    "Bra jobbat! Du är på god väg att bli en ekonomisk superhjälte!",
    "Spara som om du skulle ge bort en stor summa pengar imorgon – du vet aldrig vad som händer!",
    "Varje sparat öre är som en liten kärlekshälsning till din framtida ekonomi!",
    "Redan nu kan du känna dig som en ekonomisk mästare! Spara på!",
    "Kom ihåg, den som spar han har... mer att spendera på roliga saker senare!",
    "Den som spar den har.",
    "Ränta på ränta är som en ekonomisk superkraft! Spara på!",
    "Wer den Pfennig nicht ehrt, ist des Talers nicht wert!",
    "Verzicht ist der Anfang von Reichtum!",
    "Ein guter Tag beginnt mit einem gesparten Euro!",
    "Sparen ist sexy!",
    "Spar dich reich!",
    "Sparen macht glücklich!",
    "Sparen ist der erste Schritt zur finanziellen Freiheit!",
    "En bra buffert kan vara skillnaden mellan en liten motgång och en stor katastrof!",
];