motivationer = [
    "Tänk dig att varje sparad krona är som en liten superhjälte som kämpar för din ekonomiska frihet!",
    "Spara som om du planerade den mest episka semesterresan till en plats där pengar inte behövs!",
    "Varje sparat öre är som en applåd till din framtida jag – Bra jobbat!",
    "Kom ihåg, den som spar han har... mer att spendera på roliga saker senare!",
    "Se dina besparingar som en spel-poäng! Högre poäng = fler möjligheter!",
    "Spara idag, lev som en kung imorgon. Eller åtminstone som en väldigt nöjd hertig!",
    "Varje sparat öre är en biljett till ditt nästa stora äventyr. Packa dina väskor!",
    "Spara som om du skulle vinna en stor summa pengar imorgon – du vet aldrig vad som händer!",
    "Bra jobbat! Du är på god väg att bli en ekonomisk superhjälte!",
    "Spara som om du skulle ge bort en stor summa pengar imorgon – du vet aldrig vad som händer!",
    "Varje sparat öre är som en liten kärlekshälsning till din framtida ekonomi!",
    "Redan nu kan du känna dig som en ekonomisk mästare! Spara på!",
    "Kom ihåg, den som spar han har... mer att spendera på roliga saker senare!",
    "Den som spar den har.",
    "Ränta på ränta är som en ekonomisk superkraft! Spara på!",
    "Wer den Pfennig nicht ehrt, ist des Talers nicht wert!",
    "Verzicht ist der Anfang von Reichtum!",
    "Ein guter Tag beginnt mit einem gesparten Euro!",
    "Sparen ist sexy!",
    "Spar dich reich!",
    "Sparen macht glücklich!",
    "Sparen ist der erste Schritt zur finanziellen Freiheit!",
    "En bra buffert kan vara skillnaden mellan en liten motgång och en stor katastrof!",
    "Som de gamla grekerna sa: 'Ο οικονομικός είναι ο βασιλιάς του κόσμου!'",
    "Människan är det enda djuret som sparar pengar. Varför inte vara lite extra mänsklig idag?",
    "En sparad hundralapp idag kan vara värd mer än en hundralapp imorgon!",
    "Varför har pengar om du inte kan lägga undan dem? Spara på!",
    "Helt rätt! Spara är att vårda!",
    "Visste du att ordet 'spar' kommer från det gamla nordiska ordet 'sparr'? Inte jag heller.",
    "Du tänker rätt här. Bra jobbat!",
    "Att tjäna pengar är stort – att spara pengar är större!",
    "Kennst du den alten Spruch: 'Spare in der Zeit, dann hast du in der Not?'",
    "Spar nicht nur Geld, sondern auch Zeit und Nerven!",
    "Spar dir den Stress und leg lieber ein paar Euro zur Seite!",
    "Vägra köp och sälj!",
    "Konsum ist für Konsumenten!",
    "Sparen ist das neue Schwarz!",
    "Hörst du das? Das ist der Klang von Geld, das du nicht ausgegeben hast!",
    "Inte så tokigt va?",
    "Gar nicht mal so übel!",
    "Das reicht ja fast für eine Tasse Kaffee!",
    "Sehr gut, sparen fängt im Kopf an!",
];